---
title: "R Introduksjon"
output: html_notebook
---

```{r}
2+2
x <- 2+2
x
(y <- 3+3)
(z = 4) # ikke anbefalt 
(z = z + 2)
# remove
rm(z)
x + y
x * y
x - y
x/y
x^y
```

## Combine

```{r}
x <- c(2, 7, 9, 13)
y <- c(6, 2)
z <- x + y
z
y <- c(y, 3)
y
(z <- x + y)
```

## Typer av vektorer

```{r}
class(x)
typeof(x)
x <- 2L # uten desimaler
typeof(x)
x <- 2. # med desimaler
typeof(x)
x <- 2L
y <- 4.1
typeof(x)
typeof(y)
z <- c(x, y)
typeof(z)
z <- c(x, y, "s")
typeof(z)
z[1]
z[2]
x
y
t<- x + y
typeof(t)
z[1] + z[2]
```

R jobber med vektorer. Alle element må være av samme type. R konventerer automatisk til mer generell type.

```{r}
l <- list(x = 1:4, y =c(TRUE, FALSE, FALSE), z =  c("aa", "ba"), zz = c(2.1, 4.33))
str(l)
```

```{r}
l[c(2, 4)] # deler av listen 
l[[2]] # se forskjeller
```

## Dataframes

Dataframes har en nær slektning i Tidyverse som heter tibble

En tibble/dataframe er en liste av vektorer med **samme lengde**

```{r}
df1 <- data.frame(x =1:1000, y = rnorm(1000))
head(df1)
tail(df1)
tail(df1, n = 10)
library(tidyverse) # skriv heller i console (om det videre ikke funker)

#prefer tibble
df1_as_tib <- tibble(df1)
tib1 <- tibble(x =1:1000, y = rnorm(1000))
tib1
# samme eksempel med tekst
tib2 <- tibble(x =1:1000, y = rnorm(1000), z = rep(c("aa", "bb"), 500))
tib2
View(tib2)
```

## Help

Se help fane nede i høyre hjørne. 
```{r}
?ls
```

## Plukke tilfeldig fra tibble 

```{r}
tib2[c(1, 3)]
tib2_5 <- tib2[c(5, 77, 123, 671, 923), ]
tib2_5

# sample 
tib2[sample(x=1000, size=10), ]
```

